

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/four_joys?characeterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
server:
  port: 8090


logging:
  level:
    com.example.demo.mapper: debug
mybatis:
  mapper-locations: classpath:com/example/mapper/*.xml
  type-aliases-package: com.example.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


